### ISSUE TITLE
Incorporating our libraries

### ISSUE THREAD

**Issue by JohnReedLOL** [lihaoyi/sourcecode#10]
I have a library that is like yours, but geared more toward debugging.

I received this issue...

https://github.com/JohnReedLOL/scala-trace-debug/issues/2

My implementation has three flaws. 

One, if I want to print the expression, it is de-sugared. This is nice if you want to put all the parenthesis back, but it would be nice to have something that shows the raw source.

Two is related to performance. I need two different versions of the case where the length of the stack trace is one. One case uses Thread.currentThread.getStackTrace. Another version uses this experimental method v.tree.pos.source.content . 

Three is that if the Debug object ends up providing only macros, it might be possible to provide a master compiler option switch to turn them all off or make them just return an empty string.

In addition, there is this...

http://stackoverflow.com/questions/36189436/can-scala-macros-be-defined-inside-a-class-as-methods-of-that-class/36203449?noredirect=1#comment60071584_36203449

My macros are only available as static methods. This solution appears to allow the replacement of the implicit methods with macros so that they can also be turned off with a master command line option.

Do you have a license? If you would like to make your source code completely free to copy unrestricted, there is CC0 (creative commons zero)

John

Thank You

**Comment by lihaoyi** [comment]
It's now MIT Licensed
