### ISSUE TITLE
Full example of usage including SBT imports and example class

### ISSUE THREAD

**Issue by afinkenstadt** [lihaoyi/sourcecode#16]
In particular, what is the magic incantation to pull `sourcecode` into scope that makes the README.md examples work?

**Comment by lihaoyi** [comment]
There is no magic incantation, once you add the SBT dependencies it's in scope

```scala
"com.lihaoyi" %% "sourcecode" % "0.1.1" // Scala-JVM
"com.lihaoyi" %%% "sourcecode" % "0.1.1" // Scala.js
```

`sourcecode` is a top-level package and will be in scope once SBT includes it in your project's classpath
