### ISSUE TITLE
Hash value of source code file

### ISSUE THREAD

**Issue by ochrons** [lihaoyi/sourcecode#2]
Would it be possible to calculate a hash of the whole source file, which would then uniquely identify the version of the file being used at run-time (for example in an error log/report).

**Comment by lihaoyi** [comment]
What's the use case for this? Source files tend to depend on each other and I can't really see what the value of a single file's hash would be

**Comment by ochrons** [comment]
Yeah, I had in mind a more global version for the app, but it's probably too tedious to calculate from file hashes at compile time (+ joining them at run time). So maybe a more generic way of providing version info would work better, which doesn't really need to involve this library as it would be statically available from some generated (from a git hash) piece of code.
