### ISSUE TITLE
proguard error due to incorrectly named class

### ISSUE THREAD

**Issue by ubervison** [lihaoyi/sourcecode#21]
So I want to use uPickle in my Android project but when building my app I get this proguard warning : 

`Warning: class [sourcecode/Impls$$typecreator6$1 (haoyi-mbp's conflicted copy 2016-03-07).class] unexpectedly contains class [sourcecode.Impls$$typecreator6$1]`

sourcecode is apparently a dependency for upickle since sbt pulled it when I added the dependency for upickle.

`haoyi-mbp's conflicted copy 2016-03-07` looks suspiciously like a dropbox duplicate filename, so I hope it should be as easy to fix as just removing the conflicting file from the source tree.

**Edit:** building the jars from source and adding them manually fixed the issue.

**Comment by lihaoyi** [comment]
Boo dropbox why are you messing up my git repos
