### ISSUE TITLE
for-comprehension name support

### ISSUE THREAD

**Issue by crakjie** [lihaoyi/sourcecode#39]
```
for{
   name1 <- getName()
   name2 <- getName2(name1)
}
```

Where names functions asks for implicit sourcecode.Name.

Is that possible to have the name of name1 and name2 variable instead of $anonfun ? or maybe the name of called function `getName()` and  `getName2()`?

**Comment by fizzy33** [comment]
By the time the sourcecode macro(s) gets it that has effectively been de-sugared to
```
getName().foreach(name1 => getName2(name1).foreach(name2 =>  )
```
Not sure if/how that helps

**Comment by crakjie** [comment]
So it's mission impossible?
In this case would it be possible to have getName()(implicit self: sourcecode.Self ) giving the name of the function ?

**Comment by lihaoyi** [comment]
We should probably have sourcecode.Name walk up the owner hierarchy and
just pick the first non-anonymous name
