### ISSUE TITLE
how to get object by sourcecode Macro

### ISSUE THREAD

**Issue by jijingg** [lihaoyi/sourcecode#79]
hi @lihaoyi, i used the soucecode, it's wonderful, solved most of my problems， But I have another special need

```scala 
val x = myobj.func()
```
i want get `myobj` AST then do some on `myobj` 
something like this:
```scala 
val x = {
myobj.dofunc1
myobj.dofunc2
myobj.dofunc3
}
```

do you have any suggestion how to implement that in `somethingImpl` 
```scala 
def func()(implicit x: sourcecode.Something)

def somethingImpl(c: Context) = {
  import c.universe._
  dose there any method get q"myobj" from AST of "val x = myobj.func()" by Context
  q"""{
   $myobj.dofunc1
   $myobj.dofunc2
   $myobj.dofunc3
  """
}
```

**Comment by lihaoyi** [comment]
questions go in the gitter channel
